// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArSk93LfWyXZpgwLC1IMQvfa9bOE7hTDg',
    appId: '1:829549946241:web:ef097dbae5660638c4f480',
    messagingSenderId: '829549946241',
    projectId: 'creeruserapp',
    authDomain: 'creeruserapp.firebaseapp.com',
    storageBucket: 'creeruserapp.firebasestorage.app',
    measurementId: 'G-L82XC0MN8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApUq5LrVuzI3usiDWt1GDeysmaAsuGsdc',
    appId: '1:829549946241:android:46988132b14f8fb3c4f480',
    messagingSenderId: '829549946241',
    projectId: 'creeruserapp',
    storageBucket: 'creeruserapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJKleINKG2ZcB6kT5TQednGu7NMdLeJw8',
    appId: '1:829549946241:ios:1224c75014b4c0dcc4f480',
    messagingSenderId: '829549946241',
    projectId: 'creeruserapp',
    storageBucket: 'creeruserapp.firebasestorage.app',
    iosBundleId: 'com.example.creerUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJKleINKG2ZcB6kT5TQednGu7NMdLeJw8',
    appId: '1:829549946241:ios:1224c75014b4c0dcc4f480',
    messagingSenderId: '829549946241',
    projectId: 'creeruserapp',
    storageBucket: 'creeruserapp.firebasestorage.app',
    iosBundleId: 'com.example.creerUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArSk93LfWyXZpgwLC1IMQvfa9bOE7hTDg',
    appId: '1:829549946241:web:935e260fda667296c4f480',
    messagingSenderId: '829549946241',
    projectId: 'creeruserapp',
    authDomain: 'creeruserapp.firebaseapp.com',
    storageBucket: 'creeruserapp.firebasestorage.app',
    measurementId: 'G-7MR5SN0HK4',
  );

}